# POST http://localhost:3000/api/auth/register
# Content-Type: application/json

# {
#   "name": "Thegarmj",
#   "email": "thegarmj@gmail.com",
#   "phone": "081234567890",
#   "username": "mj123",
#   "password": "password123",
#   "confirmPassword": "password123",
#   "role": "Super Admin",
#   "terms": true
# }


POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "identity": "mj123",
  "password": "password123"
}