# # POST http://localhost:3000/api/auth/registerPatients
# Content-Type: application/json

# {
#   "name": "Faiq Ganteng",
#   "email": "faiq123@gmail.com",
#   "phone": "081234567890",
#   "username": "faiqganteng22",
#   "password": "password1231",
#   "confirmPassword": "password1231",
#   "role": "pasien",
#   "terms": true
# }



POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "identity": "faiqganteng22",
  "password": "password1231"
}